# Generated by Django 2.1.1 on 2018-10-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181018_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita_Multiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_multiple', models.CharField(default='CitaM', max_length=200)),
                ('hora_inicio', models.CharField(max_length=200)),
                ('hora_fin', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=200)),
                ('razon', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('profesor_uno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Cita_Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_simple', models.CharField(default='Cita', max_length=200)),
                ('hora_inicio', models.CharField(max_length=200)),
                ('hora_fin', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=200)),
                ('razon', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profesor')),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='asesoria_multiple',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='asesoria_simple',
        ),
        migrations.RemoveField(
            model_name='facultad',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='facultad',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='Semestre',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='seccion',
        ),
        migrations.AddField(
            model_name='curso',
            name='carrera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Carrera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='asesoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cita_Simple'),
        ),
        migrations.DeleteModel(
            name='Asesoria_multiple',
        ),
        migrations.DeleteModel(
            name='Asesoria_simple',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Facultad',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
