# Generated by Django 2.1.1 on 2018-10-19 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181018_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita_multiple',
            name='profesor_dos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_dos', to='main.Profesor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita_multiple',
            name='profesor_uno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_uno', to='main.Profesor'),
        ),
    ]
