# Generated by Django 2.1.1 on 2018-10-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_asesoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='dia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
