# Generated by Django 2.1.1 on 2018-10-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_asesoria_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita_simple',
            name='razon',
        ),
    ]
