# Generated by Django 2.1.1 on 2018-10-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_asesoria_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='asesoria',
            field=models.CharField(default='Asesoria', max_length=200),
        ),
    ]
