# Generated by Django 2.1.1 on 2018-11-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial', models.CharField(default='Asesoria', max_length=200)),
                ('dia', models.CharField(max_length=200, null=True)),
                ('lugar', models.CharField(max_length=200, null=True)),
                ('hora_inicio', models.CharField(max_length=200)),
                ('hora_fin', models.CharField(max_length=200)),
                ('razon', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(max_length=200, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profesor')),
            ],
        ),
    ]
