# Generated by Django 2.1.1 on 2018-11-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20181112_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria_Multiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesoria', models.CharField(default='AsesoriaM', max_length=200)),
                ('hora_inicio', models.CharField(max_length=200)),
                ('hora_fin', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=200)),
                ('razon', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Alumno')),
                ('profesor_dos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_dos', to='main.Profesor')),
                ('profesor_uno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_uno', to='main.Profesor')),
            ],
        ),
        migrations.RemoveField(
            model_name='cita_multiple',
            name='profesor_dos',
        ),
        migrations.RemoveField(
            model_name='cita_multiple',
            name='profesor_uno',
        ),
        migrations.DeleteModel(
            name='Cita_Multiple',
        ),
    ]
