# Generated by Django 2.1.1 on 2018-11-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_asesoria_multiple_esatado3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asesoria_multiple',
            old_name='esatado3',
            new_name='estado3',
        ),
    ]
